apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-9cne0u7wfvypj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-9cne0u7wfvypj
    app.kubernetes.io/part-of: test-gitlabrenovate-ukr8pg5ooguyv
  name: component-9cne0u7wfvypj
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-9cne0u7wfvypj
status:
  loadBalancer: {}
